# This is a basic workflow to help you get started with Actions

name: dispatcher

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          event-type: semantic
          
      # Runs a set of commands using the runners shell
      - name: dispatch
        run: curl --location --request POST 'https://api.github.com/repos/mBlomsterberg/DevOps-testing/dispatches' \
                --header 'Authorization:token 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' \
                --header 'Accept:application/vnd.github.v3+json' \
                --header 'Content-Type:application/json' \
                --data-raw '{"event_type":"semantic"}'
